site_name: Test Case Repository
site_url: https://sitename.example
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/LIG Accuver_LIG Innovative Blue.png
  favicon: assets/LIG Accuver_LIG Innovative Blue.png
  features:
    - navigation.indexes  # 카테고리 클릭 시 인덱스 페이지 바로 표시
    - navigation.expand   # 좌측 메뉴 자동 확장
    - navigation.footer
    - navigation.tags
    - search.highlight
    - search.suggest  # 검색어 자동 완성
    - search.share # 검색 결과 공유 링크

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
# plugins:
#   - search:
#       tags: true # 검색 결과에서 태그 필터링 지원

plugins:
  # - macros
  - search:
      highlight_results: true  # 검색어 하이라이트 활성화

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

  - admonition
  - pymdownx.details

nav:
  - index.md
  - Access:
    - Access: TC_Access.md
  - Voice&Video:
    - VoNR(Table): TC_VoNR.md 
    - VoLTE: TC_VoLTE.md
    - EPSFB: TC_EPSFB.md
    - ViNR: TC_ViNR.md    
    - ViLTE: TC_ViLTE.md
    - SRVCC: TC_SRVCC.md
    - CSFB: TC_CSFB.md  
    - VoWifi: TC_Vowifi.md
    # - VoNR(List): TC_VoNR(List).md
          
  - Mobility:
    - Handover: TC_Handover.md
    - Redirection: TC_Redirection.md
    - Reselection: TC_Reselection.md
    # - temp: admonitions.md
    # - temp2: code-examples.md
    # - temp3: content-tabs.md
    # - temp4: diagram-examples.md
  - Throughput:
    - Throughput: TC_Throughput.md
  - ETC:
    - Application Stationary Test: TC_Application_Stationary_Test.md
    - Backhaul IP Impairment: TC_Backhaul_IP_Impairment.md
    - DSDS: TC_DSDS.md
    - Emergency Service: TC_Emergency_Service.md
    - Feature Test: TC_Feature_Test.md
    - Link Budget: TC_Link_Budget.md
    - Message Service: TC_Message_Service.md
    - Multi-Service: TC_Multi-Service.md
    - Ping: TC_Ping.md
    - RF Performance: TC_RF_Performance.md
    - RLF Recovery: TC_RLF_Recovery.md
    - UE Capability: TC_UE_Capability.md


copyright: Copyright (C) 2026, LIG Accuver Co., Ltd