site_name: Test Case Database
site_url: https://sitename.example
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/LIG Accuver_LIG Innovative Blue.png
  favicon: assets/LIG Accuver_LIG Innovative Blue.png
  features:
    - content.tabs.link
    - navigation.indexes  # 카테고리 클릭 시 인덱스 페이지 바로 표시
    - navigation.expand   # 좌측 메뉴 자동 확장
    - navigation.footer
    - navigation.tags   # 태그 기능 활성화
    - search.highlight
    - search.suggest  # 검색어 자동 완성
    - search.share # 검색 결과 공유 링크

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
# plugins:
#   - search:
#       tags: true # 검색 결과에서 태그 필터링 지원

plugins:
  # - macros
  - search:
      highlight_results: true  # 검색어 하이라이트 활성화
      suggest: true            # 
      separator: '[\s\-\.]+'


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

  - admonition
  - pymdownx.details

nav:
  - Category: index.md
  - Access:
    - Access(154): TC_Access.md
  - Voice&Video:
    - VoNR(19): TC_VoNR.md 
    - VoLTE(38): TC_VoLTE.md
    - EPSFB(4): TC_EPSFB.md
    - ViNR(2): TC_ViNR.md    
    - ViLTE(4): TC_ViLTE.md
    - SRVCC(2): TC_SRVCC.md
    - CSFB(2): TC_CSFB.md  
    - VoWifi(1): TC_Vowifi.md
  - Mobility:
    - Handover(119): TC_Handover.md
    - Redirection(15): TC_Redirection.md
    - Reselection(10): TC_Reselection.md
  - Throughput:
    - Throughput(132): TC_Throughput.md
  - ETC:
    - Application Stationary Test(13): TC_Application_Stationary_Test.md
    - Backhaul IP Impairment(9): TC_Backhaul_IP_Impairment.md
    - DSDS(4): TC_DSDS.md
    - Emergency Service(12): TC_Emergency_Service.md
    - Feature Test(13): TC_Feature_Test.md
    - Link Budget(15): TC_Link_Budget.md
    - Message Service(30): TC_Message_Service.md
    - Multi-Service(3): TC_Multi_Service.md
    - Ping(12): TC_Ping.md
    - RF Performance(15): TC_RF_Performance.md
    - RLF Recovery(5): TC_RLF_Recovery.md
    - UE Capability(11): TC_UE_Capability.md
  


copyright: Copyright (C) 2026, LIG Accuver Co., Ltd