site_name: Cateogry of Test Case
site_url: https://sitename.example
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/LIG Accuver_LIG Innovative Blue.png
  favicon: assets/LIG Accuver_LIG Innovative Blue.png
  features:
    - navigation.footer
    - navigation.tags

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
# plugins:
#   - search:
#       tags: true # 검색 결과에서 태그 필터링 지원

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

  - admonition
  - pymdownx.details

nav:
  - index.md
  - TC Category:
    - VoNR : TC_VoNR.md
    - VoLTE: TC_VoLTE.md
    - Handover: TC_Handover.md
    - temp: admonitions.md
    - temp2: code-examples.md
    - temp3: content-tabs.md
    - temp4: diagram-examples.md

# nav:
#   - Home: index.md
#   - Test Case Database:
#       - VoNR: docs/TC_VoNR.md
#       - VoLTE: docs/TC_VoLTE.md
#       - Handover: docs/TC_Handover.md

copyright: Copyright (C) 2026, LIG Accuver Co., Ltd